############ Data Sources ############

data "aws_caller_identity" "this" {}

data "aws_region" "this" {}

############ IAM ############

data "aws_iam_policy_document" "assume_role" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
    condition {
      test     = "StringEquals"
      variable = "aws:SourceAccount"

      values = [
        data.aws_caller_identity.this.account_id
      ]
    }
  }
}

data "aws_iam_policy" "lambda" {
  name = "AWSLambdaBasicExecutionRole"
}

data "aws_iam_policy" "config" {
  name = "AWSConfigRulesExecutionRole"
}

resource "aws_iam_role" "this" {
  assume_role_policy = data.aws_iam_policy_document.assume_role.json
  name               = "config-lambda-iam"
}

resource "aws_iam_role_policy_attachment" "lambda" {
  role       = aws_iam_role.this.name
  policy_arn = data.aws_iam_policy.lambda.arn
}

resource "aws_iam_role_policy_attachment" "config" {
  role       = aws_iam_role.this.name
  policy_arn = data.aws_iam_policy.config.arn
}

############ Lambda packaging ############

data "archive_file" "this" {
  output_path = "${path.root}/.terraform/lambda_function.zip"
  source_dir  = "files/"
  type        = "zip"
}

resource "aws_lambda_function" "this" {
  architectures    = ["arm64"]
  description      = "Function for custom AWS Config rule to detect service-linked IAM roles without confused deputy protection."
  filename         = data.archive_file.this.output_path
  function_name    = "config-iam-confused-deputy"
  handler          = "lambda_function.lambda_handler"
  role             = aws_iam_role.this.arn
  runtime          = "python3.13"
  source_code_hash = data.archive_file.this.output_base64sha256
  timeout          = "30"
}

resource "aws_lambda_permission" "this" {
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.this.arn
  principal     = "config.amazonaws.com"
  statement_id  = "AllowExecutionFromConfig"
}

resource "aws_cloudwatch_log_group" "this" {
  name              = "/aws/lambda/${aws_lambda_function.this.function_name}"
  retention_in_days = "30"
}

############ Config ############

resource "aws_config_config_rule" "this" {
  description = "Custom AWS Config rule to detect service-linked IAM roles without confused deputy protection."
  input_parameters = jsonencode(
    {
      remote_iam_role_name = ""
      required_condition_keys = [
        "aws:PrincipalAccount",
        "aws:PrincipalArn",
        "aws:PrincipalOrgID",
        "aws:PrincipalOrgPaths",
        "aws:SourceAccount",
        "aws:SourceArn",
        "aws:SourceOrgID",
        "aws:SourceOrgPaths",
        "aws:ExternalId",
      ]
    }
  )
  name = "config-iam-confused-deputy"
  scope {
    compliance_resource_types = ["AWS::IAM::Role"]
  }
  source {
    owner = "CUSTOM_LAMBDA"
    source_detail {
      message_type = "ConfigurationItemChangeNotification"
    }
    source_identifier = aws_lambda_function.this.arn
  }
}

############ Monitoring ############

resource "aws_sns_topic" "this" {
  name = "${aws_lambda_function.this.function_name}-errors"
}

data "aws_iam_policy_document" "sns" {
  statement {
    sid    = "CloudWatchPublish"
    effect = "Allow"
    principals {
      type        = "AWS"
      identifiers = ["*"]
    }
    actions   = ["sns:Publish"]
    resources = [aws_sns_topic.this.arn]
    condition {
      test     = "ArnEquals"
      variable = "aws:SourceArn"
      values   = [aws_cloudwatch_metric_alarm.this.arn]
    }
  }
}

resource "aws_sns_topic_policy" "this" {
  arn    = aws_sns_topic.this.arn
  policy = data.aws_iam_policy_document.sns.json
}

resource "aws_cloudwatch_metric_alarm" "this" {
  alarm_actions       = [aws_sns_topic.this.arn]
  alarm_description   = "Alarm for errors generated by Lambda function ${aws_lambda_function.this.function_name}"
  alarm_name          = aws_lambda_function.this.function_name
  comparison_operator = "GreaterThanThreshold"
  dimensions          = { FunctionName = aws_lambda_function.this.function_name }
  evaluation_periods  = "1"
  metric_name         = "Errors"
  namespace           = "AWS/Lambda"
  period              = 60
  statistic           = "Sum"
  threshold           = 0
  treat_missing_data  = "notBreaching"
  unit                = "Count"
}
